# Generated by Django 4.0.5 on 2022-06-22 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateTimeField(verbose_name='post pub date')),
                ('user_img', models.ImageField(upload_to='user_img')),
                ('user_name', models.CharField(max_length=30, verbose_name='Username who published post')),
                ('post_img', models.ImageField(upload_to='posts')),
                ('likes', models.DecimalField(decimal_places=0, max_digits=5)),
                ('comments', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_img', models.ImageField(upload_to='user_img')),
                ('user_name', models.CharField(max_length=30, verbose_name='Username')),
                ('posts', models.DecimalField(decimal_places=0, max_digits=5)),
                ('subscribers', models.DecimalField(decimal_places=0, max_digits=5)),
                ('subscriptions', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_img', models.ImageField(upload_to='user_img')),
                ('user_name', models.CharField(max_length=30, verbose_name='Username who published post')),
                ('author_comment_text', models.TextField(max_length=300, verbose_name='Comment text')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
        ),
    ]
